version: 2
updates:
  # Enable version updates for npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier*"
          - "vitest*"
          - "jest*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "tsup*"
          - "@changesets/*"
          - "rollup*"
          - "vite*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Ignore major version updates for these critical packages
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
    reviewers:
      - "yourusername" # Replace with actual maintainer
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "ci"
    reviewers:
      - "yourusername" # Replace with actual maintainer