name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current pain point?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - CLI Command
        - Validation Check
        - Code Generation
        - Documentation
        - Framework Integration
        - Performance
        - Developer Experience
        - Other
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: Who would benefit from this feature?
      options:
        - label: New FlowLock users
        - label: Existing FlowLock users
        - label: AI/Agent developers
        - label: Framework developers
        - label: Enterprise users

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how this feature would be used
      placeholder: |
        ```bash
        uxcg new-command --option value
        ```
        
        ```json
        {
          "newFeature": {
            "enabled": true
          }
        }
        ```

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to write documentation for this feature