export const GLOSSARY_TEMPLATE = `# FlowLock Glossary
# This file defines derived and external fields referenced in uxspec.json

# Derived Fields
# Fields that are calculated or generated by the system
derived:
  - term: createdAt
    definition: Timestamp when the record was created
    formula: new Date().toISOString()
    tags: [system, timestamp]
  
  - term: updatedAt
    definition: Timestamp when the record was last modified
    formula: new Date().toISOString()
    tags: [system, timestamp]
  
  - term: id
    definition: Unique identifier for the record
    formula: crypto.randomUUID()
    tags: [system, identifier]
  
  - term: slug
    definition: URL-friendly version of the name
    formula: name.toLowerCase().replace(/[^a-z0-9]+/g, '-')
    tags: [system, url]
  
  - term: fullName
    definition: Combination of first and last name
    formula: firstName + ' ' + lastName
    tags: [computed]
  
  - term: age
    definition: Calculated from birth date
    formula: Math.floor((Date.now() - birthDate) / (365.25 * 24 * 60 * 60 * 1000))
    tags: [computed]

# External Fields
# Fields that come from external systems
external:
  - term: avatar
    definition: User profile picture
    source: Gravatar API
    tags: [external, image]
  
  - term: weatherData
    definition: Current weather information
    source: OpenWeather API
    tags: [external, realtime]
  
  - term: stockPrice
    definition: Current stock price
    source: Yahoo Finance API
    tags: [external, financial]
  
  - term: geolocation
    definition: User's current location
    source: Browser Geolocation API
    tags: [external, location]

# Business Terms
# Domain-specific terminology
business:
  - term: customer
    definition: A person or organization that purchases products or services
    tags: [entity, business]
  
  - term: order
    definition: A request to purchase products or services
    tags: [entity, business]
  
  - term: invoice
    definition: A bill for products or services provided
    tags: [entity, financial]
  
  - term: subscription
    definition: Recurring service agreement
    tags: [entity, recurring]

# FlowLock Terms
# Framework-specific terminology
flowlock:
  - term: inventory
    definition: Runtime extraction of database entities, API endpoints, and UI interactions
    tags: [framework, analysis]
  
  - term: runtimeDeterminism
    definition: Validation that ensures consistent behavior across database, auth, and UI layers
    tags: [framework, validation]
  
  - term: uxspec
    definition: UX specification file that defines screens, entities, roles, and interactions
    tags: [framework, configuration]
  
  - term: honest
    definition: Screen reads are properly captured, derived, or external
    tags: [framework, validation]
  
  - term: creatable
    definition: Entity that can be created through the UI with proper validation
    tags: [framework, validation]
  
  - term: reachability
    definition: All screens can be reached within a certain number of navigation steps
    tags: [framework, validation]

# States
# Valid states for entities
states:
  order:
    - draft: Order is being prepared
    - submitted: Order has been submitted for processing
    - approved: Order has been approved
    - processing: Order is being fulfilled
    - shipped: Order has been shipped
    - delivered: Order has been delivered
    - cancelled: Order has been cancelled
  
  user:
    - pending: User registration pending verification
    - active: User account is active
    - suspended: User account is temporarily suspended
    - deactivated: User account is permanently deactivated
  
  payment:
    - pending: Payment is being processed
    - completed: Payment successful
    - failed: Payment failed
    - refunded: Payment has been refunded
`;

export const GLOSSARY_YML_TEMPLATE = `# FlowLock Glossary (YAML format)
# Defines derived and external fields for uxspec.json

derived:
  createdAt:
    definition: "Timestamp when the record was created"
    formula: "new Date().toISOString()"
    tags: ["system", "timestamp"]
  
  updatedAt:
    definition: "Timestamp when the record was last modified"
    formula: "new Date().toISOString()"
    tags: ["system", "timestamp"]
  
  id:
    definition: "Unique identifier for the record"
    formula: "crypto.randomUUID()"
    tags: ["system", "identifier"]

external:
  avatar:
    definition: "User profile picture"
    source: "Gravatar API"
    tags: ["external", "image"]
  
  weatherData:
    definition: "Current weather information"
    source: "OpenWeather API"
    tags: ["external", "realtime"]
`;

export function createGlossaryFiles(): { [key: string]: string } {
  return {
    "uxspec/glossary.md": GLOSSARY_TEMPLATE,
    "uxspec/glossary.yml": GLOSSARY_YML_TEMPLATE,
  };
}
